name: My GitHub Action Workflow

on:
  push:
    branches:
      - main

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Use Variables in the workflow
      env:
        MESSAGE: Hello Message
      run: |
        echo $JOB_ENV
        echo $STEP_ENV
        echo ${{ env.MESSAGE }}
        echo ${{ github.repository.MESSAGE }}
        echo ${{ vars.MESSAGE }}
        echo ${{ secrets.MESSAGE }}
